name: 哔咔自动签到

on:
  schedule:
    - cron: '0 10 * * *' # 定时任务，修改为你需要的时间
  workflow_dispatch: # 添加这个事件支持手动触发

jobs:
  sign_in:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: 安装依赖
        run: pip install httpx

      - name: 执行签到脚本
        env:
          ACCOUNT_LIST: ${{ secrets.ACCOUNT_LIST }}
          EMAIL_CONFIG: ${{ secrets.EMAIL_CONFIG }}
        run: python script.py
         
